import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar";
import { Footer } from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.className} antialiased bg-gray-200`}>
        <div className="min-h-screen flex flex-col relative">
          <div className="fixed top-5 left-5 right-5 z-50">
            <Navbar />
          </div>
          <main className="flex-1">{children}</main>
          {/* <Footer></Footer> */}
        </div>
      </body>
    </html>
  );
}
